name = "PLists"
uuid = "244549da-a957-11e8-2419-29f9eea8ace5"
authors = ["Erik Engheim <erik.engheim@mac.com>"]
version = "1.1.3"

[compat]
julia = "1.4"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
